service: refarch-ecs-python-service

plugins:
  - serverless-parameters

custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"

  parameters:
    ServiceName:
      Type: String
      Description: "Service name"
      Default: "${self:service}"

    ServiceVersion:
      Type: String
      Description: "Service release build"
      Default: 'latest'

    ServiceMemory:
      Type: Number
      Description: "Service memory in GB"
      Default: 128

    ServicePort:
      Type: Number
      Description: "Serivce port"
      Default: 8080

    ServiceInstancesMin:
      Type: Number
      Description: "Minimum number of task instances"
      Default: "${env:SVC_INST_MIN, '3'}"

    ServiceInstancesMax:
      Type: Number
      Description: "Maximum number of task instances"
      Default: "${env:SVC_INST_MAX, '4'}"

    VpcId:
      Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
      Description: "VPC ID"
      Default: "/infra/vpc/prime/VpcId"

    AlbListener:
      Type: AWS::SSM::Parameter::Value<String>
      Description: "ARN of ECS cluster ALB Listener"
      Default: "/refarch-ecs/${self:provider.stage}/AlbListener"

    UrlPath:
      Type: String
      Description: "Path to register with ALB"
      Default: "/${self:service}-${self:provider.stage}"

    EcsServiceDefaultPolicyArn:
      Type: AWS::SSM::Parameter::Value<String>
      Description: "IAM policy ARN for ECS cluster"
      Default: "/refarch-ecs/${self:provider.stage}/EcsServiceDefaultPolicyArn"

    InitDeploy:
      Type: String
      Description: "Create only projectbasics"
      AllowedValues:
        - true
        - false
      Default: "${env:INIT_DEPLOY, 'false'}"

provider:
  name: aws
  stage: "${self:custom.stage}"
  cfnRole: "${ssm:/infra/deploy/prime/DeployRoleArn}"
  stackTags:
    x-service: "${self:service}"
    x-stack: "${self:service}-${self:provider.stage}"

resources:

  Conditions:
    IsNotInitDeploy:
      Fn::Equals:
        - Ref: InitDeploy
        - false

  Resources:
    CloudWatchLogsGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName:
          Ref: AWS::StackName
        RetentionInDays: 365

    EcrRepo:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName:
          Ref: AWS::StackName

    TaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
        Family:
          Ref: ServiceName
        ContainerDefinitions:
          - Name:
              Ref: AWS::StackName
            Essential: true
            Image:
              Fn::Join:
                - ":"
                - - Fn::GetAtt:
                    - EcrRepo
                    - Arn
                  - Ref: ServiceVersion
            Memory:
              Ref: ServicePort
            PortMappings:
              - ContainerPort:
                  Ref: ServicePort
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group:
                  Ref: CloudWatchLogsGroup
                awslogs-region:
                  Ref: AWS::Region

    ServiceRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Statement:
            Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action:
              - sts:AssumeRole
        ManagedPolicyArns:
          - Ref: EcsServiceDefaultPolicyArn

    TargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        VpcId:
          Ref: VpcId
        Port: 80
        Protocol: HTTP
        Matcher:
          HttpCode: 200
        HealthCheckIntervalSeconds: 10
        HealthCheckPath:
          Fn::Join:
            - '/'
            - - Ref: UrlPath
              - 'health'
        HealthCheckProtocol: HTTP
        HealthCheckTimeoutSeconds: 5
        HealthyThresholdCount: 2

    ListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        ListenerArn:
          Ref: AlbListener
        Priority: 2
        Conditions:
          - Field: path-pattern
            Values:
              - Ref: UrlPath
        Actions:
          - TargetGroupArn:
              Ref: TargetGroup
            Type: forward

    EcrRepoUrlSsmParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: "/${self:service}/${self:provider.stage}/EcrRepoUrl"
        Description: "URL of ECR repository"
        Type: String
        Value:
          Fn::Join:
            - ''
            - - Ref: AWS::AccountId
              - '.dkr.ecr.'
              - Ref: AWS::Region
              - '.amazonaws.com/'
              - Ref: EcrRepo
